# Generated by Django 5.2.1 on 2025-05-28 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteMaestro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_comprobante', models.CharField(help_text='Número único generado por el sistema para el comprobante (ej: COMP00001).', max_length=50, unique=True, verbose_name='Número de Comprobante')),
                ('fecha_comprobante', models.DateField(help_text='Fecha en que ocurrió la transacción.', verbose_name='Fecha del Comprobante')),
                ('fecha_contabilizacion', models.DateField(help_text='Fecha en que el comprobante fue registrado en el sistema contable.', verbose_name='Fecha de Contabilización')),
                ('tipo_comprobante', models.CharField(choices=[('DIARIO', 'Comprobante Diario'), ('INGRESO', 'Comprobante de Ingreso'), ('EGRESO', 'Comprobante de Egreso'), ('TRANSFERENCIA', 'Comprobante de Transferencia')], default='DIARIO', max_length=20, verbose_name='Tipo de Comprobante')),
                ('descripcion', models.TextField(help_text='Descripción breve del propósito general del comprobante.', verbose_name='Descripción General')),
                ('total_debito', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Total Débito')),
                ('total_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Total Crédito')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONTABILIZADO', 'Contabilizado'), ('ANULADO', 'Anulado'), ('BORRADOR', 'Borrador')], default='PENDIENTE', max_length=20, verbose_name='Estado del Comprobante')),
                ('tipo_documento_fuente', models.CharField(blank=True, help_text='Ej: Factura, Recibo de Caja, Nómina.', max_length=50, null=True, verbose_name='Tipo de Documento Fuente')),
                ('id_documento_fuente', models.IntegerField(blank=True, help_text='ID del documento en su tabla original (ej: ID de la Factura).', null=True, verbose_name='ID del Documento Fuente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comprobante Contable',
                'verbose_name_plural': 'Comprobantes Contables',
                'ordering': ['-fecha_comprobante', '-numero_comprobante'],
            },
        ),
        migrations.CreateModel(
            name='CuentaMayor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_cuenta', models.CharField(help_text='Código único para la cuenta principal (ej: 110505).', max_length=20, unique=True, verbose_name='Código de Cuenta')),
                ('nombre_cuenta', models.CharField(help_text='Nombre de la cuenta principal (ej: Caja General).', max_length=100, verbose_name='Nombre de Cuenta')),
                ('esta_activa', models.BooleanField(default=True, help_text='Indica si la cuenta está activa para transacciones.', verbose_name='¿Está Activa?')),
                ('permite_transacciones', models.BooleanField(default=True, help_text='Indica si se pueden registrar transacciones directamente en esta cuenta (algunas son solo para agrupación).', verbose_name='¿Permite Transacciones Directas?')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta Mayor',
                'verbose_name_plural': 'Cuentas Mayores',
                'ordering': ['codigo_cuenta'],
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: Activo, Pasivo, Ingresos.', max_length=50, unique=True, verbose_name='Nombre del Tipo de Cuenta')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo de cuenta.', null=True, verbose_name='Descripción')),
                ('naturaleza_cuenta', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], help_text='Define si la cuenta aumenta con débitos o créditos.', max_length=10, verbose_name='Naturaleza de la Cuenta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cuenta',
                'verbose_name_plural': 'Tipos de Cuentas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('fecha_factura', models.DateField(verbose_name='Fecha de Factura')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('tipo_factura', models.CharField(choices=[('VENTA', 'Venta'), ('COMPRA', 'Compra')], max_length=20, verbose_name='Tipo de Factura')),
                ('nombre_cliente_proveedor', models.CharField(blank=True, help_text='Nombre del cliente o proveedor asociado a la factura.', max_length=200, null=True, verbose_name='Nombre Cliente/Proveedor')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Total')),
                ('monto_impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Monto Impuestos')),
                ('moneda', models.CharField(default='COP', help_text='Código ISO 4217 de la moneda (ej: COP, USD).', max_length=3, verbose_name='Moneda')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('PAGADA', 'Pagada'), ('PAGADA_PARCIALMENTE', 'Pagada Parcialmente'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20, verbose_name='Estado de Factura')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comprobante_maestro', models.OneToOneField(blank=True, help_text='Comprobante contable generado a partir de esta factura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_asociada', to='contabilidad.comprobantemaestro', verbose_name='Comprobante Contable Asociado')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_factura', '-numero_factura'],
            },
        ),
        migrations.CreateModel(
            name='SubCuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_sub_cuenta', models.CharField(help_text='Código único para la sub-cuenta (ej: 11050501).', max_length=20, unique=True, verbose_name='Código de Sub-Cuenta')),
                ('nombre_sub_cuenta', models.CharField(help_text='Nombre de la sub-cuenta (ej: Caja Menor).', max_length=100, verbose_name='Nombre de Sub-Cuenta')),
                ('esta_activa', models.BooleanField(default=True, verbose_name='¿Está Activa?')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cuenta_mayor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcuentas', to='contabilidad.cuentamayor', verbose_name='Cuenta Mayor')),
            ],
            options={
                'verbose_name': 'Sub-Cuenta',
                'verbose_name_plural': 'Sub-Cuentas',
                'ordering': ['codigo_sub_cuenta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleComprobante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto_debito', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Monto Débito')),
                ('monto_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Monto Crédito')),
                ('descripcion_linea', models.CharField(blank=True, help_text='Descripción específica de esta parte del asiento.', max_length=255, null=True, verbose_name='Descripción de la Línea')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comprobante_maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.comprobantemaestro', verbose_name='Comprobante Principal')),
                ('cuenta_mayor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_comprobante', to='contabilidad.cuentamayor', verbose_name='Cuenta Mayor Contable')),
                ('sub_cuenta', models.ForeignKey(blank=True, help_text='Opcional, si la transacción afecta una sub-cuenta específica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_comprobante', to='contabilidad.subcuenta', verbose_name='Sub-Cuenta Contable')),
            ],
            options={
                'verbose_name': 'Detalle del Comprobante',
                'verbose_name_plural': 'Detalles del Comprobante',
                'ordering': ['comprobante_maestro', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cuentamayor',
            name='tipo_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_mayores', to='contabilidad.tipocuenta', verbose_name='Tipo de Cuenta'),
        ),
    ]
