# Generated by Django 5.2.1 on 2025-05-28 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('RECIBO', 'Recibo de Pago'), ('NOTA_ENTREGA', 'Nota de Entrega'), ('JUSTIFICANTE_PAGO', 'Justificante de Pago'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Breve descripción del comprobante.', null=True)),
                ('archivo', models.FileField(upload_to='comprobantes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='contabilidad.factura')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
