# Generated by Django 5.2 on 2025-05-01 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCli', models.CharField(max_length=45)),
                ('cedulaCli', models.IntegerField(unique=True)),
                ('emailCli', models.EmailField(max_length=45, unique=True)),
                ('telefonoCli', models.IntegerField()),
                ('idRestaurante', models.IntegerField(verbose_name=models.ForeignKey(db_column='idRestaurante', on_delete=django.db.models.deletion.DO_NOTHING, to='account.restaurantes'))),
            ],
            options={
                'db_table': 'Clientes',
                'managed': True,
            },
        ),
    ]
