# Generated by Django 5.2 on 2025-05-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cedulaCli',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='emailCli',
            field=models.EmailField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
