# Generated by Django 5.1.7 on 2025-04-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='telefonoEmpleado',
            field=models.CharField(max_length=17),
        ),
    ]
