# Generated by Django 5.2 on 2025-05-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_empleado_telefonoempleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='puestoEmpleado',
        ),
        migrations.AddField(
            model_name='empleado',
            name='integer_selection',
            field=models.IntegerField(choices=[(6, 'Cajero'), (5, 'Mesero'), (1, 'Chef'), (7, 'Limpieza'), (3, 'Ayudante - cocina'), (2, 'Cocinero'), (4, 'Lavaplatos')], default=2),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('e.cap', 'En Capacitacion'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=8),
        ),
    ]
