# Generated by Django 5.2.1 on 2025-05-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_empleado_puestoempleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='documento_path',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='integer_selection',
        ),
        migrations.AddField(
            model_name='documentos',
            name='documento',
            field=models.FileField(default='', upload_to='hojas_de_vida/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('capacitacion', 'En Capacitacion'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], default='inactivo'),
        ),
    ]
