# Generated by Django 5.2.1 on 2025-05-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_empleado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='salarioEmpleado',
            field=models.CharField(choices=[(1, 3000000), (2, 2500000), (3, 1800000), (4, 1500000), (5, 2000000), (6, 2200000), (7, 1600000)], max_length=20),
        ),
    ]
