# Generated by Django 5.2.1 on 2025-05-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_empleado_salarioempleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='salarioEmpleado',
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('cocinero', 'Cocinero'), ('limpieza', 'Limpieza'), ('ayudante', 'Ayudante - cocina'), ('cajero', 'Cajero'), ('chef', 'Chef'), ('lavaplatos', 'Lavaplatos'), ('mesero', 'Mesero')], default='cocinero', max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario',
            field=models.CharField(choices=[('chef', 3000000), ('cocinero', 2500000), ('ayudante', 1800000), ('lavaplatos', 1500000), ('mesero', 2000000), ('cajero', 2200000), ('limpieza', 1600000)], default='', max_length=20),
            preserve_default=False,
        ),
    ]
