# Generated by Django 5.2.1 on 2025-05-28 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_empleado_salarioempleado_empleado_puesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='idEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('cocinero', 'Cocinero'), ('mesero', 'Mesero'), ('lavaplatos', 'Lavaplatos'), ('cajero', 'Cajero'), ('chef', 'Chef'), ('limpieza', 'Limpieza'), ('ayudante', 'Ayudante - cocina')], default='cocinero', max_length=50),
        ),
    ]
