# Generated by Django 5.2.1 on 2025-05-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_documentos_idempleado_alter_empleado_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('lavaplatos', 'Lavaplatos'), ('cajero', 'Cajero'), ('mesero', 'Mesero'), ('ayudante', 'Ayudante - cocina'), ('chef', 'Chef'), ('cocinero', 'Cocinero'), ('limpieza', 'Limpieza')], default='cocinero', max_length=50),
        ),
        migrations.CreateModel(
            name='EvaluacionDesempeno',
            fields=[
                ('idEvaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('evaluador', models.CharField(default='Gerente', max_length=100)),
                ('fecha_evaluacion', models.DateField(auto_now_add=True)),
                ('criterios', models.TextField()),
                ('puntuacion', models.IntegerField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.empleado')),
            ],
            options={
                'db_table': 'EvaluacionDesempeno',
                'managed': True,
            },
        ),
    ]
