# Generated by Django 5.2 on 2025-04-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerentes',
            fields=[
                ('idGerente', models.AutoField(primary_key=True, serialize=False)),
                ('nombreGer', models.CharField(max_length=45)),
                ('emailGer', models.EmailField(max_length=45)),
                ('telefonoGer', models.IntegerField()),
                ('passwordGer', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Gerentes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Restaurantes',
            fields=[
                ('idRestaurante', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRes', models.CharField(max_length=45)),
                ('direccionRes', models.CharField(max_length=45)),
                ('idGerente', models.IntegerField(verbose_name=models.ForeignKey(db_column='idGerente', on_delete=django.db.models.deletion.DO_NOTHING, to='account.gerentes'))),
            ],
            options={
                'db_table': 'Restaurantes',
                'managed': True,
            },
        ),
    ]
