-- MySQL Script generated by MySQL Workbench
-- Sat Apr 19 08:10:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `nombreEmpleado` VARCHAR(100) NOT NULL,
  `apellidoEmpleado` VARCHAR(100) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `direccionEmpleado` VARCHAR(300) NOT NULL,
  `telefonoEmpleado` VARCHAR(12) NOT NULL,
  `emailEmpleado` VARCHAR(100) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `puestoEmpleado` VARCHAR(100) NOT NULL,
  `salarioEmpleado` DECIMAL(10) NOT NULL,
  `estado` VARCHAR(8) GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Capacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Capacitacion` (
  `idCapacitacion` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `nombre_curso` VARCHAR(255) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `Calificacion` DOUBLE NOT NULL,
  PRIMARY KEY (`idCapacitacion`),
  INDEX `idEmpleado_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `idEmpleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Desempeño`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Desempeño` (
  `idDesempeño` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `fecha_evaluacion` DATE NOT NULL,
  `Evaluador` VARCHAR(100) NOT NULL,
  `Calificacion` DECIMAL NOT NULL,
  `Comentarios` LONGTEXT NOT NULL,
  PRIMARY KEY (`idDesempeño`),
  INDEX `idEmpleado_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `idEmpleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Beneficios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Beneficios` (
  `idBeneficios` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `tipo_beneficio` VARCHAR(45) NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  PRIMARY KEY (`idBeneficios`),
  INDEX `idEmpleado_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `idEmpleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Permiso` (
  `idPermiso` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `tipo_permiso` VARCHAR(45) NOT NULL,
  `Permisocol` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  PRIMARY KEY (`idPermiso`),
  INDEX `idEmpleado_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `idEmpleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado_departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado_departamento` (
  `idEmpleado` INT NOT NULL,
  `idDepartamento` INT NOT NULL,
  INDEX `idEmpleado_idx` (`idEmpleado` ASC, `idDepartamento` ASC) VISIBLE,
  CONSTRAINT `idEmpleado`
    FOREIGN KEY (`idEmpleado` , `idDepartamento`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado` , `idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDepartamento`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Departamento` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Posicion_Laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Posicion_Laboral` (
  `idPosicion` INT NOT NULL,
  `Puesto_trabajo` INT NOT NULL,
  `IdDepartamento` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  PRIMARY KEY (`idPosicion`),
  INDEX `idDepartamento_idx` (`IdDepartamento` ASC) VISIBLE,
  CONSTRAINT `idDepartamento`
    FOREIGN KEY (`IdDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pago` (
  `idPagos` INT NOT NULL,
  `idEmpleado` INT NULL,
  `Salario` DOUBLE NOT NULL,
  `Bonos` DOUBLE NULL,
  `Impuestos` DOUBLE NULL,
  `Salario_neto` DOUBLE NOT NULL,
  `Inicio_periodo_pago` DATE NOT NULL,
  `Fin_periodo_pago` DATE NULL,
  `Fecha_pago` DATE NOT NULL,
  PRIMARY KEY (`idPagos`),
  INDEX `idEmpleado_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `idEmpleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asistencia` (
  `idAsistencia` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `entrada` TIME NOT NULL,
  `salida` TIME NULL,
  `dia_trabajo` DATE NULL,
  `estado` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idAsistencia`),
  INDEX `idEmpleado_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `idEmpleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Documentos` (
  `idDocumentos` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `tipo_documento` VARCHAR(45) NOT NULL,
  `fecha_actualizacion` DATE NOT NULL,
  `documento_path` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDocumentos`),
  INDEX `idEmpleado_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `idEmpleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
